---
title: "Fine_mapping"
output: html_document
date: "2026-05-05"
---
```{r}
library(data.table)

sumstats_all <- fread("/data/circ_ukb/AHua/project/GWAS/regenie/height/metaanalysis/height_{feature}_all_metal1.txt")

colnames(sumstats_all)

sumstats_all[, c("chr", "pos", "ref", "alt") := tstrsplit(MarkerName, ":", fixed = TRUE)]

sumstats_all[, chr := as.integer(gsub("chr", "", chr))]
sumstats_all[, pos := as.integer(pos)]

sumstats_all[, ID := paste0("chr", chr, ":", pos, ":", alt, ":", ref)]

target_chr <- 1
target_pos <- 150709379
start <- target_pos - 500000
end <- target_pos + 500000
```


```{r}
# extract summary stat in the region
sumstats_region <- sumstats_all[chr == target_chr & pos >= start & pos <= end]
cat(" summary region SNP number: ", nrow(sumstats_region), "\n")

bim <- fread("/data/circ_ukb/AHua/MGB_array/GSA_53k/GSA_53K.hg38.bim", header = FALSE)
setnames(bim, c("CHR", "SNP", "CM", "BP", "A1", "A2"))

bim_region <- bim[CHR == target_chr & BP >= start & BP <= end]
cat("extract BIM interval SNP number: ", nrow(bim_region), "\n")

bim_region[, ID := paste0("chr", CHR, ":", BP, ":", A1, ":", A2)] 

merged <- merge(sumstats_region, bim_region[, .(ID, SNP, CHR, BP)], by = "ID")

cat( nrow(merged), "\n")
```


```{r}
#LD
module load Plink/1.9

plink \
--bfile /data/circ_ukb/AHua/MGB_array/GSA_53k/GSA_53K.hg38 \
--chr 7 \
--from-bp 37031495 \
--to-bp   38031495 \
--r square \
--out /data/circ_ukb/AHua/fine_mapping/chr7_region_ld_1mb


merged[, Z := Effect / StdErr]
summary(merged$Z)

```

```{r}
#SUSIE

library(data.table)
library(susieR)

ld_mat <- as.matrix(fread("/data/circ_ukb/AHua/fine_mapping/chr7_region_ld_1mb.ld", header = FALSE))

snp_ld <- merged$SNP  


ld_trimmed <- ld_mat[1:length(snp_ld), 1:length(snp_ld)]


n_sample <- max(merged$TotalSampleSize, na.rm = TRUE)


susie_out <- susie_rss(
  z = merged$Z,
  R = ld_trimmed,
  L = 5,                    
  n = n_sample,
  standardize = TRUE
)

print(susie_out$sets)

```

